### ISSUE TITLE
No Image in Rich Presence

### ISSUE THREAD

**Issue by SNTCphil** [Unickorn/discordtidal#4]
![image](https://user-images.githubusercontent.com/103654044/163408607-44421d5a-d1d3-4d32-8f05-05dba3db8590.png)
The Image inside the Rich pressence doesn´t work for me at all
I love your effort and you coded exactly what I was searching for, but this small thing is needed for the perfection

**Comment by unickorn** [comment]
Thank you for creating an issue! Unfortunately since I no longer have a TIDAL account, it will be a bit hard to debug this. Could you tell me what branch you're using (unsafe or safe) and show me the application assets in https://discord.com/developers/applications ?
It should be under Rich Presence
<img width="719" alt="image" src="https://user-images.githubusercontent.com/29836508/163410498-818154b7-b7ac-445e-a790-0e3190531c99.png">

**Comment by SNTCphil** [comment]
Im using the unsafe branch, here my assets
![image](https://user-images.githubusercontent.com/103654044/163412237-d5a55c09-b8a3-4a85-a765-d5ec48addbda.png)
The assets seem to work, this is what confuses me, the images seem to be there and are also added in the moment a new song is playing, already checked this

**Comment by unickorn** [comment]
It usually takes a while for discord to update their asset cache after them being uploaded there. Can you upload this and name it "tidal"? That we can see if discordtidal is completely messing up or just showing an inexistent tidal placeholder.
![tidal](https://user-images.githubusercontent.com/29836508/163413023-98a307be-5dc3-47d4-b991-f5aa20dfacda.png)

**Comment by SNTCphil** [comment]
Yes, the Placeholder is used now

**Comment by SNTCphil** [comment]
ok, I replayed some old songs, they are also imaged now, it probably just took a while for discord to load the images when played the first time or smth, ok tysm for your Work!

**Comment by unickorn** [comment]
Glad I could help and thank you for the support! :)
